// Concept demo data, ported verbatim from flipscope_final_polished.html.
// Used by pages whose backing features land in Beta (Phases 3-4).
/* eslint-disable */
export const seed = {project:{address:'212 E Maple',city:'Perry, Oklahoma',purchase:119500,arv:205000,sqft:1380,beds:3,baths:2,status:'Active Rehab'},scope:[{room:'Kitchen',trade:'Demo',task:'Remove existing cabinets and countertops',qty:1,unit:'LS',labor:1600,material:250,status:'Ready',proof:true},{room:'Kitchen',trade:'Cabinets',task:'Install shaker cabinets',qty:18,unit:'LF',labor:110,material:165,status:'Scheduled',proof:true},{room:'Kitchen',trade:'Countertops',task:'Install quartz countertops',qty:42,unit:'SF',labor:22,material:56,status:'Planned',proof:true},{room:'Whole House',trade:'Flooring',task:'Install LVP flooring',qty:1260,unit:'SF',labor:2.1,material:2.8,status:'In Progress',proof:true},{room:'Bathroom',trade:'Tile',task:'Tile shower walls',qty:92,unit:'SF',labor:7.5,material:4.25,status:'Planned',proof:true},{room:'Exterior',trade:'Paint',task:'Prep and paint exterior',qty:1,unit:'LS',labor:4200,material:1800,status:'Planned',proof:false}],costs:[{cat:'Purchase',budget:119500,actual:119500,committed:119500},{cat:'Demo',budget:5500,actual:4200,committed:5200},{cat:'Kitchen',budget:24500,actual:11200,committed:22100},{cat:'Flooring',budget:8400,actual:3500,committed:7900},{cat:'Bathrooms',budget:12000,actual:2800,committed:9800},{cat:'Paint',budget:7000,actual:0,committed:5800},{cat:'HVAC/Electrical',budget:9500,actual:6100,committed:8700}],materials:[{name:'Shaker White Cabinets',vendor:"Lowe's",qty:1,unit:'Set',price:5180,status:'Ordered'},{name:'Carrara Quartz',vendor:'Fabricator',qty:42,unit:'SF',price:56,status:'Selected'},{name:'Driftwood Oak LVP',vendor:"Lowe's",qty:1320,unit:'SF',price:2.8,status:'Delivered'},{name:'Matte Black Faucet',vendor:'Amazon',qty:1,unit:'EA',price:189,status:'Selected'}],schedule:[
{task:'Remove existing cabinets and countertops',trade:'Demo',room:'Kitchen',scopeIndex:0,startDate:'2026-08-10',durDays:3,status:'Done',progress:100},
{task:'Install shaker cabinets',trade:'Cabinets',room:'Kitchen',scopeIndex:1,startDate:'2026-08-17',durDays:5,status:'Scheduled',progress:0},
{task:'Install quartz countertops',trade:'Countertops',room:'Kitchen',scopeIndex:2,startDate:'2026-08-24',durDays:3,status:'Planned',progress:0},
{task:'Install LVP flooring',trade:'Flooring',room:'Whole House',scopeIndex:3,startDate:'2026-08-20',durDays:6,status:'In Progress',progress:35},
{task:'Tile shower walls',trade:'Tile',room:'Bathroom',scopeIndex:4,startDate:'2026-08-27',durDays:4,status:'Planned',progress:0},
{task:'Prep and paint exterior',trade:'Paint',room:'Exterior',scopeIndex:5,startDate:'2026-08-31',durDays:5,status:'Planned',progress:0}
],feed:[{icon:'✓',title:'Flooring delivery received',meta:'Today · Materials'},{icon:'📷',title:'6 progress photos uploaded',meta:'Today · Kitchen'},{icon:'$',title:'Kitchen invoice approved — $3,850',meta:'Yesterday · Financials'},{icon:'↗',title:'Change Order #2 sent for approval',meta:'Yesterday · Change Orders'}],punch:[{room:'Kitchen',title:'Adjust cabinet door',status:'Open',proof:true},{room:'Bath',title:'Re-caulk shower corner',status:'Open',proof:true}],changes:[{title:'Replace damaged subfloor',amount:1850,status:'Approved'},{title:'Upgrade kitchen lighting',amount:975,status:'Pending'}],logs:[{date:'Aug 15',work:'Kitchen cabinets delivered. Electrical rough-in complete.',crew:5,weather:'Clear 91°F'}],transcript:'',captureScope:[],style:'Modern',designPicks:[],deal:{financing:4200,holding:6200,sellingPct:7,contingency:6500,targetMargin:18},bids:[{trade:'Cabinets',vendor:'Red River Millwork',amount:7200,days:5,rating:4.8,status:'Preferred'},{trade:'Cabinets',vendor:'Sooner Cabinets',amount:6650,days:8,rating:4.5,status:'Quoted'},{trade:'Flooring',vendor:'Perry Flooring Co',amount:7450,days:4,rating:4.7,status:'Quoted'}],approvals:[{title:'Kitchen finish package',type:'Selection',amount:7721,status:'Approved'},{title:'Subfloor change order',type:'Change Order',amount:1850,status:'Approved'},{title:'Exterior paint color',type:'Selection',amount:0,status:'Pending'}],members:[{name:'Brad',role:'Owner / Admin',access:'Full'},{name:'Project Manager',role:'PM',access:'Projects + Financials'},{name:'Field Crew',role:'Field',access:'Schedule + Proof'},{name:'Investor',role:'Viewer',access:'Reports + Approvals'}],risks:[{level:'High',title:'Cabinet lead time may move install',impact:'Schedule +4 days',action:'Award preferred vendor today'},{level:'Medium',title:'Kitchen committed cost at 90% of budget',impact:'Margin compression',action:'Freeze nonessential upgrades'},{level:'Low',title:'Exterior paint weather window',impact:'2 day exposure',action:'Watch forecast before mobilization'}],closeout:[{title:'Final punch complete',status:'Open'},{title:'Lien waivers collected',status:'Open'},{title:'Final permit inspections',status:'Open'},{title:'Before / after gallery complete',status:'Done'},{title:'Warranty packet delivered',status:'Open'}],warranties:[{item:'HVAC',vendor:'Mechanical contractor',expires:'2031-08-15',status:'Active'},{item:'Roof',vendor:'Roofing contractor',expires:'2036-08-15',status:'Active'}],
actions:[
{type:'Procurement',title:'Award cabinet vendor today',detail:'Current lead time threatens countertop installation.',priority:'High',status:'Open',financial:550,schedule:4},
{type:'Financial',title:'Review kitchen budget variance',detail:'Kitchen commitments are approaching the approved budget.',priority:'High',status:'Open',financial:3850,schedule:0},
{type:'Field',title:'Collect electrical completion proof',detail:'Electrical rough-in is marked complete but verification media is missing.',priority:'Medium',status:'Open',financial:0,schedule:1},
{type:'Approval',title:'Approve exterior paint color',detail:'Selection is still pending and blocks procurement.',priority:'Medium',status:'Open',financial:0,schedule:2}
],
forecast:{finalCost:169450,profit:35550,roi:21.0,finish:'Sep 12',riskScore:31,costConfidence:82,scheduleConfidence:76},
cashflow:[
{week:'Aug 17',outflow:12200,inflow:0,cumulative:12200},
{week:'Aug 24',outflow:19300,inflow:0,cumulative:31500},
{week:'Aug 31',outflow:14800,inflow:0,cumulative:46300},
{week:'Sep 7',outflow:7100,inflow:0,cumulative:53400}
],
copilot:[{role:'assistant',content:'I am watching scope, costs, schedule, procurement and field verification. Ask what needs attention, what to order, where margin is at risk, or how much cash the project needs.'}]
}
